epi052/feroxbuster

src/heuristics.rs
src/logger.rs
src/progress.rs
src/scanner.rs
src/utils.rs
tests/test_heuristics.rs

logging and bars print nicely; closes #38

---

.github/workflows/rust-ci.yml
Cargo.toml

39 fix ci cd pipeline

---

.github/workflows/rust-ci.yml

fixed CI so that it triggers on master properly

---

Dockerfile
README.md

added Dockerfile based on alpine. Includes wordlists

---

Cargo.toml
src/config.rs
src/heuristics.rs
src/lib.rs
src/logger.rs
src/main.rs
src/reporter.rs
src/scanner.rs
src/utils.rs
tests/test_heuristics.rs

Capture logging in logfile

---

src/banner.rs
src/config.rs
src/parser.rs
tests/test_banner.rs

added -e|--extract-links to parser/banner/config 🕵

---

Cargo.toml
src/extractor.rs
src/lib.rs

Feature add link extraction  add extractor for html

---

Cargo.toml
README.md
src/extractor.rs
src/heuristics.rs
src/lib.rs
src/main.rs
src/reporter.rs
src/scanner.rs
src/utils.rs
tests/test_extractor.rs

Integrate extractor::get_links into scanner v2

---

Cargo.toml
src/banner.rs
src/main.rs

Check for Updates on Startup

---

.github/workflows/build.yml

add strip to linux and macos binaries

---

src/scanner.rs

fixed progress bar being incremented too little

---

Cargo.toml
README.md
ferox-config.toml.example
src/banner.rs
src/config.rs
src/parser.rs
tests/test_banner.rs

added --scan-limit option

---

src/filters.rs
src/heuristics.rs
src/lib.rs
src/scanner.rs

Added new filter system to allow for extending with different filter types

---

Cargo.toml
README.md
ferox-config.toml.example
src/banner.rs
src/client.rs
src/config.rs
src/heuristics.rs
src/parser.rs
src/reporter.rs
src/scanner.rs
src/utils.rs
tests/test_banner.rs
tests/test_extractor.rs
tests/test_heuristics.rs

added --filter-status option 

---

src/filters.rs
src/scanner.rs
tests/test_filters.rs
tests/test_scanner.rs

implemented deny list

---

Cargo.toml
README.md
ferox-config.toml.example
src/banner.rs
src/client.rs
src/config.rs
src/filters.rs
src/heuristics.rs
src/lib.rs
src/parser.rs
src/reporter.rs
src/scanner.rs
src/utils.rs
tests/test_banner.rs
tests/test_extractor.rs
tests/test_filters.rs
tests/test_heuristics.rs
tests/test_scanner.rs

Feature response code blacklist

---

Cargo.toml
src/heuristics.rs
src/lib.rs
src/main.rs
src/reporter.rs
src/scanner.rs
tests/test_banner.rs
tests/test_config.rs
tests/test_heuristics.rs
tests/test_main.rs

logging initialized early enough to display all intended log messages

---

src/banner.rs
src/parser.rs
tests/test_banner.rs

added replay options to banner and parser

---

src/reporter.rs
tests/test_scanner.rs

implemented replay proxy

---

Cargo.toml
src/lib.rs
src/main.rs
src/utils.rs

added auto-adjustment of open file limit

---

Cargo.toml
src/scanner.rs

Fix directory extraction bug

---

.github/workflows/check.yml
Cargo.toml
README.md
ferox-config.toml.example
src/banner.rs
src/config.rs
src/heuristics.rs
src/lib.rs
src/parser.rs
src/reporter.rs
src/scanner.rs
tests/test_banner.rs

Add wordcount and line count filtering to address #89

---

src/client.rs
src/filters.rs
src/heuristics.rs
src/lib.rs
src/logger.rs
src/parser.rs
src/reporter.rs
src/scanner.rs
src/utils.rs

initial guess at grabbing the correct info

---

src/filters.rs

added new filter

---

Cargo.toml
ferox-config.toml.example
src/banner.rs
src/config.rs
src/parser.rs
tests/test_banner.rs
tests/test_extractor.rs

added most of the support structure for --filter-regex

---

src/main.rs
src/scanner.rs
tests/test_banner.rs
tests/test_scanner.rs

simplified call to scanner::initialize

---

Cargo.toml
README.md
src/extractor.rs
src/main.rs
src/scanner.rs
tests/test_extractor.rs

137 extract robots txt

---

.github/workflows/build.yml
Cargo.toml
README.md
ferox-config.toml.example
shell_completions/_feroxbuster
shell_completions/_feroxbuster.ps1
shell_completions/feroxbuster.bash
shell_completions/feroxbuster.fish
src/banner.rs
src/config.rs
src/filters.rs
src/lib.rs
src/main.rs
src/parser.rs
src/scan_manager.rs
src/scanner.rs
tests/test_banner.rs
tests/test_filters.rs

add similar page filter

---

Cargo.toml
src/banner.rs
src/config.rs
src/event_handlers/mod.rs
src/event_handlers/statistics.rs
src/filters/mod.rs
src/lib.rs
src/main.rs
src/reporter.rs
src/scan_manager.rs
src/scanner.rs
src/statistics/command.rs
src/statistics/container.rs
src/statistics/data.rs
src/statistics/error.rs
src/statistics/field.rs
src/statistics/init.rs
src/statistics/macros.rs
src/statistics/mod.rs
src/statistics/tests.rs
src/utils.rs
tests/test_banner.rs
tests/test_extractor.rs
tests/test_scanner.rs

2.0 statistics restructure

---

src/banner/container.rs
src/banner/entry.rs
src/banner/mod.rs
src/banner/tests.rs
src/event_handlers/mod.rs
src/filters/mod.rs
src/lib.rs
src/scanner.rs
src/traits.rs

restructured banner

---

src/client.rs
src/config.rs
src/extractor/container.rs

rewrote client; updated tests

---

src/heuristics.rs
src/main.rs
src/scanner.rs
src/utils.rs
tests/test_banner.rs

rewrote heuristics

---

src/event_handlers/inputs.rs
src/event_handlers/mod.rs
src/main.rs
src/scan_manager.rs
tests/test_scanner.rs

added terminal input event handlers

---

Cargo.toml
src/event_handlers/scans.rs
src/extractor/container.rs
src/filters/init.rs
src/filters/mod.rs
src/lib.rs
src/main.rs
src/response.rs
src/scanner.rs

scanner rewrite

---

Cargo.lock
Cargo.toml
Makefile

Fix makefile for kali repos

---

Cargo.lock
Cargo.toml
src/event_handlers/command.rs
src/event_handlers/scans.rs
src/main.rs
src/scanner/ferox_scanner.rs

changed wordlist read so that ordering is maintained 

---

.cargo/config
.github/workflows/build.yml
Cargo.lock
Cargo.toml
README.md
src/statistics/container.rs

officially support arm builds

---

README.md

blabla it's just two line in a MD README, the checks are meant for code

add blackarch install

---

install-nix.sh

check for unzip before continuing

---

Cargo.lock
Cargo.toml
src/filters/tests.rs
src/filters/wildcard.rs
src/statistics/container.rs

335 fix wildcard filter when response is zero

---

Cargo.lock
Cargo.toml
src/banner/container.rs
src/config/container.rs
src/event_handlers/command.rs
src/event_handlers/container.rs
src/event_handlers/inputs.rs
src/event_handlers/scans.rs
src/event_handlers/statistics.rs
src/extractor/container.rs
src/extractor/tests.rs
src/filters/init.rs
src/heuristics.rs
src/response.rs
src/scan_manager/menu.rs
src/scan_manager/mod.rs
src/scan_manager/scan_container.rs
src/scan_manager/tests.rs
src/scanner/ferox_scanner.rs
src/scanner/requester.rs
src/statistics/container.rs
src/statistics/macros.rs
src/statistics/tests.rs
src/url.rs

429 add orig url to json output

---

.github/pull_request_template.md
build.rs
src/response.rs
src/scanner/ferox_scanner.rs
src/scanner/requester.rs
src/utils.rs
tests/test_heuristics.rs

Add redirect messages to normal reports

---

build.rs

Remove superfluous if statement

---

Cargo.lock
Cargo.toml

updated deps

---

Cargo.lock
Cargo.toml
shell_completions/_feroxbuster
shell_completions/_feroxbuster.ps1
shell_completions/feroxbuster.bash
shell_completions/feroxbuster.elv
src/config/container.rs
src/parser.rs
tests/test_parser.rs

updated clap from 3.x to 4.x

---

.github/workflows/build.yml
src/scan_manager/scan.rs
src/scan_manager/scan_container.rs
src/scan_manager/tests.rs
tests/test_scan_manager.rs

661 fix double dir scan

---

src/extractor/builder.rs
src/extractor/container.rs
src/extractor/tests.rs

fixed invalid uri exception during extraction

---

Cargo.lock
src/event_handlers/container.rs
src/event_handlers/scans.rs
src/event_handlers/statistics.rs
src/scan_manager/scan.rs

fix resume with offset

---

README.md

Update alternative installation method for brew and chocolatey

---

Cargo.lock
Cargo.toml

add http/2 support

---

ferox-config.toml.example

fixes issue https://github.com/epi052/feroxbuster/issues/1151

fixes #1151

---

build.rs
shell_completions/feroxbuster.fish

Because of a typo, the Fish completions weren't being updated for the past 4 years. I fixed the type and ran to build script to update the completion script.
I didn't open an issue beforehand since the fix is pretty trivial.

Regenerate fish completions

---

src/event_handlers/command.rs
src/event_handlers/scans.rs
src/lib.rs
src/scan_manager/menu.rs
src/scan_manager/scan_container.rs
src/scan_manager/tests.rs
src/scanner/ferox_scanner.rs
src/scanner/tests.rs
src/sync/dynamic_semaphore.rs
src/sync/mod.rs
tests/test_dynamic_semaphore.rs

increase scan limit via scan management menu

---

src/extractor/container.rs

fixed bug filed under issue #1077

---

src/heuristics.rs
src/statistics/container.rs
src/statistics/error.rs
src/utils.rs

improve ssl error message

---

ferox-config.toml.example
shell_completions/_feroxbuster
shell_completions/_feroxbuster.ps1
shell_completions/feroxbuster.bash
shell_completions/feroxbuster.elv
shell_completions/feroxbuster.fish
src/banner/container.rs
src/config/container.rs
src/config/tests.rs
src/config/utils.rs
src/event_handlers/outputs.rs
src/extractor/container.rs
src/extractor/tests.rs
src/filters/utils.rs
src/heuristics.rs
src/parser.rs
src/response.rs
src/scan_manager/tests.rs
src/scanner/requester.rs
tests/test_banner.rs
tests/test_response_size_limit.rs
tests/test_scan_manager.rs

add max size read option
