epi052/feroxbuster

- README.md
Hi!
Thanks for releasing feroxbuster, it looks really fresh and has an intuitive approach to the job at hand ❤️ 
I had a look over at the README.md and have a few additions regarding `ffuf` functionalities to the comparison matrix. Some of them are a bit vague, so feel free to disagree and I'll change the PR accordingly. I'm trying to explain them here in the description.
- multiple target scan (via stdin or multiple -u)
- As `ffuf` supports multiple wordlists, it's possible to use a wordlist for a list of hostnames. This list can also be supplied from STDIN (see the last entry in this list)
- can accept urls via STDIN as part of a pipeline
- Same as the above
- can accept wordlists via STDIN
- Ffuf can read wordlists (for hostnames, urls, headers whatever) from STDIN when using `-` as …
> [Documentation] README.md matrix fixes for ffuf

- Dockerfile
Docker container
- based on alpine
- uses latest release
- includes default wordlists cloned into `/usr/share/seclists`
```
docker run --init -it feroxbuster -u http://example.com -x js,html
```
```
cat targets.txt | docker run --net=host --init -i feroxbuster --stdin -x js,html --proxy socks5://127.0.0.1:9050
```
```
alias feroxbuster="docker run --init -i feroxbuster"
```
> added Dockerfile based on alpine. Includes wordlists

- src/utils.rs
> timeouts logged as warnings, other errors remain the same

- Cargo.toml
- src/scanner.rs
> fixed duplicate directory scans

- README.md
I've had to change the AUR package name from `feroxbuster` to [`feroxbuster-git`](https://aur.archlinux.org/packages/feroxbuster-git) in order to meet Arch Linux's [VCS package guidelines](https://wiki.archlinux.org/index.php/VCS_package_guidelines). This pull request just updates the package name in the README so that users download the correct package (the old one will soon be unavailable).
> Update AUR Package Name

- src/utils.rs
> Fix handling of urls found in wordlists

- README.md
This is an enhancement to documentation and is related to #126. It adds a small section that covers:
* The subtle difference in impact to system resources the usage of green threads has
* The exact implementation details of `-t` and `-L`
* A few simple example usages of `-t` and `-L` with an explanation of their effect on a scan
> Documentation: Clarification on green threads and the behavior of -t and -L

- .github/pull_request_template.md
- Cargo.toml
- src/filters.rs
- src/main.rs
- src/scanner.rs
- src/utils.rs
- tests/test_filters.rs
> Reimplement size-based filters using FeroxFilter trait

- README.md
> updated readme for 1.8.0

- Cargo.toml
- README.md
- ferox-config.toml.example
- src/banner.rs
- src/config.rs
- src/filters.rs
- src/main.rs
- src/parser.rs
- src/scanner.rs
- tests/test_banner.rs
- tests/test_extractor.rs
- tests/test_scanner.rs
> 136 add regex filter

- .github/pull_request_template.md
- .github/workflows/check.yml
- Cargo.toml
- README.md
- ferox-config.toml.example
- src/config.rs
- src/filters.rs
- src/lib.rs
- src/main.rs
- src/parser.rs
- src/progress.rs
- src/reporter.rs
- src/scan_manager.rs
- src/scanner.rs
- tests/test_banner.rs
- tests/test_scan_manager.rs
> add ability to resume scans

- .gitignore
- Cargo.toml
- shell_completions/_feroxbuster
- src/config.rs
- src/main.rs
- src/parser.rs
- src/scan_manager.rs
- tests/test_scanner.rs
> allow CLI args to work w/ --resume-from

- src/banner.rs
- src/extractor.rs
- tests/test_extractor.rs
- tests/test_filters.rs
- tests/test_heuristics.rs
- tests/test_main.rs
- tests/test_scan_manager.rs
- tests/test_scanner.rs
> added emoji fallback when terminals dont support; updated httpmock

- Cargo.toml
- src/main.rs
- src/scanner.rs
- tests/test_heuristics.rs
> fixed issue where only one initial feroxscan was issued

- Cargo.toml
- src/utils.rs
> fixed url parsing issue when word starts with 2 or more /

- Cargo.lock
- Cargo.toml
- src/config/container.rs
- src/heuristics.rs
- tests/test_banner.rs
- tests/test_heuristics.rs
- tests/test_main.rs
Added SSL specific error to "could not connect message" fixes #219 
The errors thrown by clippy appear to be the same errors thrown when manually running
`cargo clippy --all-targets --all-features -- -D warnings -A clippy::deref_addrof` against the main branch of the official repository.
> Added SSL specific error to "could not connect message" fixes #219 

- .github/workflows/build.yml
- Cargo.toml
- src/parser.rs
- tests/test_parser.rs
> added small check for help param to always print and exit

- Cargo.lock
- Cargo.toml
- README.md
- src/event_handlers/inputs.rs
- src/main.rs
- src/utils.rs
- tests/test_main.rs
- tests/test_scan_manager.rs
> Log to separate files when using --parallel

- .github/workflows/cicd-to-dockerhub.yml
- Dockerfile
This PR fixes and modifies the Dockerfile in feroxbuster with the following considerations:
- Adds deterministic base images for reproducible builds.
- Adds a multi-stage build that reduces the image size from about 78MB to 13MB.
- Added a least-privileged user in compliance with Docker security best practices.
We also have a workflow with a CICD pipeline to DockerHub. All you need to do is to add the DOCKER_HUB_USERNAME and DOCKER_HUB_ACCESS_TOKEN secrets to the repository and all pushes/merges to the master branch will automatically push an image to DockerHub.
> Optimize Dockerfile and implement CI/CD to DockerHub

- shell_completions/_feroxbuster
- shell_completions/_feroxbuster.ps1
- shell_completions/feroxbuster.bash
- shell_completions/feroxbuster.fish
- src/config/container.rs
- src/main.rs
- src/parser.rs
I added some code to accept a `key=value` pair for cookies using the `--cookies` flag or the `-b` shorthand. The cookies can still be added using the longer `--header` flag way.
> I've written some code to implement this feature.
_Originally posted by @7047payloads in https://github.com/epi052/feroxbuster/issues/442#issuecomment-1004090323_
> Added support for specifying cookies with the `-b` flag

- Cargo.lock
- Cargo.toml
- src/scanner/requester.rs
I'm looking over how leaky-bucket was used prior to 0.11, which introduced self-coordinating rate limiters (no coordinator task running in the background needed) and noticed this project. This bumps leaky-bucket to the latest version (0.12.1), the largest difference is that the default refill interval is changed from 1 second to 100ms so it has to be specified where it previously was not.
I looked over the contributor checklist and everything is OK except there not being a separate issue for this bump. If you want me to create a separate issue please advise.
> Bump leaky-bucket to 0.12.1

- CONTRIBUTING.md
- Dockerfile
Fixes #761
My first public PR, be gentle if I have managed to screw this up😄 
> Fixes #761 | Updated Dockerfile and CONTRIBUTING docs

- src/event_handlers/command.rs
- src/event_handlers/scans.rs
- src/event_handlers/statistics.rs
- src/main.rs
- src/scan_manager/scan.rs
- src/scan_manager/tests.rs
- tests/test_scan_manager.rs
> resume scan starts from offset in wordlist

- src/scan_manager/scan_container.rs
> Showing banner again after finish scan management menu

- .gitignore
- LICENSE
- choco_package/feroxbuster.nuspec
- choco_package/legal/LICENSE.txt
- choco_package/legal/VERIFICATION.txt
- choco_package/tools/chocolateyinstall.ps1
- choco_package/tools/chocolateyuninstall.ps1
Fixes https://github.com/epi052/feroxbuster/issues/763
push the package to chocolatey using your API credential as explained in this page https://docs.chocolatey.org/en-us/create/create-packages-quick-start
Push the package to the Chocolatey community package repository:
- Get a Chocolatey account:
- [Register](https://chocolatey.org/account/register)
- Copy the API key from [your Chocolatey account](https://chocolatey.org/account).
```
choco apikey --api-key [API_KEY_HERE] -source https://push.chocolatey.org/
choco push package-name.1.1.0.nupkg --source https://push.chocolatey.org/ - nupkg file can be omitted if it is the only one in the directory.
```
So, every release of feroxbuster need to be pushed on chocolatey too. I think this can be automated using github workflow.
Long form …
> Adding feroxbuster as chocolatey package

- src/event_handlers/outputs.rs
- src/nlp/document.rs
- src/nlp/term.rs
- src/scanner/ferox_scanner.rs
- tests/test_filters.rs
> fixed collect backups filtering

- shell_completions/_feroxbuster
- shell_completions/_feroxbuster.ps1
- shell_completions/feroxbuster.elv
- src/config/container.rs
- src/config/utils.rs
- src/parser.rs
- src/response.rs
- src/scan_manager/scan.rs
- src/scan_manager/scan_container.rs
> allow --json in conjunction with --silent

- .github/workflows/build.yml
- src/banner/container.rs
- src/client.rs
> remove scan info from update check

- src/response.rs
> fixed issue where --silent included too much info on found dir

- install-nix.sh
Fontconfig allows fonts to be installed in many places.
This PR queries fontconfig to see if it knows about a Noto Color Emoji font to decide whether to install the font instead of just checking ~/.fonts.
I didn't create an issue because this is literally a one line change and the PR is self explanatory imo.
> query fontconfig to determine if Noto Color Emoji is installed

- .github/workflows/winget.yml
- README.md
- Related to https://github.com/epi052/feroxbuster/issues/763
[This action](https://github.com/vedantmgoyal2009/winget-releaser) automatically generates manifests for Winget Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.
feroxbuster has been recently added to Winget (https://github.com/microsoft/winget-pkgs/pull/154219), and this workflow will be used to update it.
**Before merging this:**
1. Add a **classic** PAT with `public_repo` scope as a repository secret named `WINGET_TOKEN`.
2. Fork https://github.com/microsoft/winget-pkgs under @epi052. The action will use that fork for making a branch and creating a PR with the upstream [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository on every release.
3. Install …
> ci: add winget releaser workflow

- .github/workflows/winget.yml
I'm not sure why the `release` trigger did not trigger, but anyhow, I added a tag name input to the `workflow_dispatch` trigger to fix the workflow failure.
> Fix `workflow_dispatch` trigger for Winget workflow

- shell_completions/_feroxbuster
- src/parser.rs
> url now conflicts with parallel

- .gitignore
- CONTRIBUTING.md
> docs: replace -Zprofile with instrument-coverage
